---
title: "Taking A Look"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# keeping track of the code that each script requires! Reproducible
```

## Exploratory Analysis

What's in our data? Let's take a look through some plots.

```{r fulltidy plots}
colnames(fulltidy)
# looking at individual sentences/instances to look at how standard the data are
fullset %>% slice_sample(n = 5) %>% pull(Dialogue)
# most popular words
fulltidy %>% count(Word, sort = TRUE) %>% 
  filter(n > 1000) %>% 
  ggplot(aes(fct_reorder(Word, n),n)) +
  geom_col() +
  coord_flip() +
  labs(x = NULL)
```


```{r fulltidy plots}
filter(n < 500)
# zipf's law = nl follows log scale, log-log plot w/ rank?


fulltidy %>% count(Word, sort = TRUE) %>% 
  filter(n > 500) %>% 
  ggplot(aes(Word,n)) +
  geom_col() +
  coord_flip()

####Bar Charts (n) By Role####
par(mfrow=c(1,2))

fulltidy %>% 
  filter(Role == 1) %>% 
  count(Word, sort = TRUE) %>% 
  filter(n > 200) %>% 
  ggplot(aes(Word,n)) +
  geom_col(aes(color = n)) +
#  geom_text(aes(label = Word), check_overlap = TRUE, vjust = 1.5) +
  labs(x = NULL, title = "Words: Persuadee") +
  coord_flip()

fulltidy %>% 
  filter(Role == 0) %>% 
  count(Word, sort = TRUE) %>% 
  filter(n > 500) %>% 
  ggplot(aes(Word,n)) +
  geom_col(aes(color = n)) +
#  geom_text(aes(label = Word), check_overlap = TRUE, vjust = 1.5) +
  labs(x = NULL, title = "Words: Persuader") +
  coord_flip()
par(mfrow=c(1,1))

#####Bar Charts (n/sum(n) by Role####
# proportional, persuadee bar
fulltidy %>% 
  filter(Role == 1) %>% 
  count(Word, sort = TRUE) %>% 
  mutate(proportion = n / sum(n)) %>% 
  ggplot(aes(Word,proportion)) +
  geom_jitter(aes(color = n)) +
  geom_text(aes(label = Word), check_overlap = TRUE, vjust = 1.5) +
  labs(x = NULL, title = "Words: Persuadee") +
  coord_flip()

# proportional, persuader bar
fulltidy %>% 
  filter(Role == 0) %>% 
  count(Word, sort = TRUE) %>% 
  mutate(proportion = n / sum(n)) %>% 
  ggplot(aes(Word,proportion)) +
  geom_jitter(aes(color = n)) +
  geom_text(aes(label = Word), check_overlap = TRUE, vjust = 1.5) +
  labs(x = NULL, title = "Words: Persuader") +
  coord_flip()

```

## Including Plots


```{r annset plots, echo=FALSE}
# plot multiple things against actual donation
# plot of actual donation v stated donation
annset %>% 
#  filter(IntDonation < 5000) %>% 
  ggplot() +
  geom_boxplot(aes(IntDonation))
annset %>% 
  ggplot() +
  geom_boxplot(aes(Donation))

annset %>% 
  #difference between IntDonation and Donation
  filter(IntDonation < 75) %>% 
  ggplot(aes(Donation-IntDonation)) +
  geom_histogram(binwidth = 10)
```
There are two outliers with respect to x, one where someone promise to donate \$10,000 but didn't, and another where someone promised to donate \$500 and didn't.
```{r fullset plots, echo=FALSE}
# distributions for each personality trait (one of those bar plots that is stacked/filled)

# utterances per conversation
fullset %>% 
  count(ConvoId) %>% 
  ggplot(aes(n)) +
  geom_histogram()

# the big five [extrovert, agreeable, conscientious, neurotic, open]
full_i_raw %>% 
  select(B3,extrovert:open) %>% 
  pivot_longer(extrovert:open,names_to = "trait", values_to = "score") %>% 
  ggplot(aes(score, fill = trait)) +
  facet_wrap(~trait) +
  geom_histogram(bins = 5, show.legend = FALSE)

# the moral foundations [extrovert, agreeable, conscientious, neurotic, open]
full_i_raw %>% 
  select(B3,care:freedom) %>% 
  pivot_longer(care:freedom,names_to = "trait", values_to = "score") %>% 
  ggplot(aes(score, fill = trait)) +
  facet_wrap(~trait) +
  geom_histogram(bins = 6, show.legend = FALSE)

# the Schwartz Portrait [extrovert, agreeable, conscientious, neurotic, open]
full_i_raw %>% 
  select(B3,conform:security) %>% 
  pivot_longer(conform:security,names_to = "trait", values_to = "score") %>% 
  ggplot(aes(score, fill = trait)) +
  facet_wrap(~trait) +
  geom_histogram(bins = 6, show.legend = FALSE)

# the decision making style [extrovert, agreeable, conscientious, neurotic, open]
full_i_raw %>% 
  select(B3,rational:intuitive) %>% 
  pivot_longer(rational:intuitive,names_to = "trait", values_to = "score") %>% 
  ggplot(aes(score, fill = trait)) +
  facet_wrap(~trait) +
  geom_histogram(bins = 5, show.legend = FALSE)

# # 10 baby plots of value plots
# full_i_raw %>% 
#   select(B3,fairness:self_direction) %>% 
#   pivot_longer(fairness:self_direction,names_to = "trait", values_to = "score") %>% 
#   ggplot(aes(score, fill = trait)) +
#   facet_wrap(~trait) +
#   geom_histogram(bins = 6, show.legend = FALSE)



# 3 barcharts for education/ideology
full_i_raw %>% 
  count(edu,ideology) %>% 
  mutate(ideology = factor(ideology,c("Conservative","Moderate","Liberal"))) %>% 
  # reoder education levels
  filter(!is.na(edu), !is.na(ideology)) %>% 
  ggplot(aes(ideology,n,fill = ideology)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~edu,scales = "free")

# one (or more) similar plots with other info
# more exploratory plots
# wrap race age X income 
full_i_raw %>% 
  filter(!is.na(age),!is.na(income)) %>% 
  ggplot(aes(age,income)) +
  geom_jitter() +
  facet_wrap(~race) 
  

# wrap race age X income
full_i_raw %>% 
  filter(!is.na(age),!is.na(income)) %>% 
  ggplot(aes(age,income)) +
  geom_jitter() +
  facet_wrap(~edu)

# wrap race age X income
ggplot(aes(age,income)) +
  geom_jitter() +
  facet_wrap(~marital)

# stacked barchart education/ideology
full_i_raw %>% 
  count(edu,ideology) %>% 
  mutate(ideology = factor(ideology,c("Conservative","Moderate","Liberal"))) %>% 
  # reorder education levels
  filter(!is.na(edu), !is.na(ideology)) %>% 
  ggplot(aes(edu,n,fill = ideology)) +
  geom_col()

# dodge barchart education/ideology
full_i_raw %>% 
  count(edu,ideology) %>% 
  mutate(ideology = factor(ideology,c("Conservative","Moderate","Liberal"))) %>% 
  # reoder education levels
  filter(!is.na(edu), !is.na(ideology)) %>% 
  ggplot(aes(edu,n,fill = ideology)) +
  geom_col(position = "dodge")

# dodge barchart religion/ideology
full_i_raw %>% 
  count(religion,ideology) %>% 
  mutate(ideology = factor(ideology,c("Conservative","Moderate","Liberal"))) %>% 
  # reoder education levels
  filter(!is.na(religion), !is.na(ideology)) %>% 
  ggplot(aes(religion,n,fill = ideology)) +
  geom_col(position = "dodge")

full_i_raw %>% 
  count(religion,ideology) %>% 
  mutate(religion = as.factor(religion)) %>% 
  # reoder education levels
  filter(!is.na(religion), !is.na(ideology)) %>% 
  ggplot(aes(ideology,n,fill = religion)) +
  geom_col(position = "dodge")

```

## More Plots!
```{r other plots}
# plots for frequency of (top) words and donation amount
# have to use the id_tdf words to organize by top words that ISN'T a stop word


# top words by personality trait and role
# have to use the id_tdf words to organize by top words that ISN'T a stop word

```

