---
title: "Zipf's Law"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# source('wk01/source.R')
```

```{r import, child='../data/import.Rmd'}

```

## Zipf's Law
Words are fancy. And that kind of what Zipf's law says. It says that word frequency is inversely proportional to its rank. So what? 
```{r wordcount}
############## Group = ConvoId #########
# two group by, one by conversation and one by total words in the sample
words1 = fullset %>% 
  select(ConvoId,
         Dialogue,
         NumTurn
        ) %>% 
  unnest_tokens(Word,Dialogue) %>% 
  count(ConvoId,Word,sort = TRUE, name = "Count")

words2 = words1 %>% 
  group_by(ConvoId) %>% 
  summarize(ctotal = sum(Count))

wordcount <- left_join(words1, words2)

############# Group = Corpus #######
# group by total words in the sample
wordcount1 = fullset %>%
  select(ConvoId,
         Dialogue,
         NumTurn
        ) %>%
  unnest_tokens(Word,Dialogue) %>%
  count(Word,sort = TRUE, name = "Count")

# words22 = words11 %>%
#   summarize(ctotal = sum(Count))
# 
# wordcount1 <- left_join(words11, words22)

# these two datasets look extremely familiar... maybe bc they're both joined on ConvoId?

# ####### Group = NumSet ######
# # two group by, one by number of turns and one by total words in the sample
# words111 = fullset %>% 
#   select(ConvoId,
#          Dialogue,
#          NumTurn
#         ) %>% 
#   unnest_tokens(Word,Dialogue) %>% 
#   count(NumTurn,Word,sort = TRUE, name = "Count")
# 
# words222 = words111 %>% 
#   group_by(NumTurn) %>% 
#   summarize(ctotal = sum(Count))
# 
# wordcount2 <- left_join(words111, words222)

```


What do the distributions of the words look like compared to their conversation?
```{r word frequency}
###########ConvoId#### 
wordcount %>% 
  ggplot(aes(Count/ctotal)) +
  geom_histogram(bins = 15) +
  labs(title = 'Word Usage per Conversation', x = "proportion", y = '# of words')

###########Corpus#####
wordcount1 %>% 
  ggplot(aes(Count)) +
  geom_histogram(bins = 20) +
  scale_x_log10() +
  labs(title = 'Word Frequency', x = '# of occurences per word', y = '# of words')

###########Numset##### 
# wordcount2 %>% 
#   ggplot(aes(Count/ctotal)) +
#   geom_histogram(bins = 15) +
#   labs(title = 'Word Frequency per Number of Turns', x = '# of occurences per words', y = 'proportions')
# 
# wordcount2 %>% 
#   ggplot(aes(Count/ctotal, fill = as.factor(NumTurn))) +
#   geom_histogram(show.legend = FALSE) +
#   xlim(NA, 0.0009) +
#   facet_wrap(~NumTurn, ncol = 2, scales = "free_y")
# wordcount2 %>% # to look at the number of values in each factor
#   ggplot(aes(NumTurn)) + 
#   geom_histogram()
# summary(as.factor(fullset$NumTurn))

```


## Rank and Frequency
```{r frequency/rank}
# by convo_id
freq_by_rank <- wordcount %>%
  group_by(ConvoId) %>%
  mutate(rank = row_number(),
         `term frequency` = Count/ctotal)

# corpus, no by variable
freq_by_rank1 <- wordcount1 %>% 
  mutate(rank = row_number(),
         `term frequency` = Count)

# freq_by_rank2 <- wordcount2 %>% 
#   group_by(NumTurn) %>% 
#   mutate(rank = row_number(), 
#          `term frequency` = Count/ctotal)
# summary(log10(freq_by_rank2[6]))
```


```{r zipfslaw}
# Zipf's law plot - group by ConvoId
freq_by_rank %>%
  ggplot(aes(rank, `term frequency`, color = ConvoId)) +
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) +
  scale_x_log10() +
  scale_y_log10()
# extremely noisy! not improved by removing 'color = '

# Zipf's law plot - corpus
freq_by_rank1 %>% 
  ggplot(aes(rank, `term frequency`)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
# very straight

# # Zipf's law plot - group by NumTurn
# freq_by_rank2 %>% 
#   ggplot(aes(rank, `term frequency`, color = as.factor(NumTurn))) + 
#   geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
#   scale_x_log10() +
#   scale_y_log10()
# # only seven groups rather than 1,000


# # 
# rank_subset = freq_by_rank %>% 
#   filter(rank < 100, # what would be the middle range of this data?
#          rank > 5)
# 
# lm(log10(`term frequency`) ~ log10(rank), data = rank_subset)

rank_subset = freq_by_rank1 %>% 
  filter(rank > 100) # what would be the middle range of this data?

rank_model1 = lm(log10(`term frequency`) ~ log10(rank), data = freq_by_rank1)

rank_model11 = lm(log10(`term frequency`) ~ log10(rank), data = rank_subset)

# rank_subset2 = freq_by_rank2 %>% 
#   filter(rank < 1000,
#          rank > 10)
# 
# lm(log10(`term frequency`) ~ log10(rank), data = rank_subset2)
```


